[username]
format = "[$user]($style) ğŸ  "
disabled = false
show_always = true

[character]
format = "$symbol"
success_symbol = "[ğŸŒ¼](bold green) "
error_symbol = "[ğŸŒº](bold red) "

[directory]
truncate_to_repo = false
